version: '3.8'

services:
  django:
    build:
      context: .
    container_name: speciarium
    ports:
      - "8000:8000"
    volumes:
      - ./src/media:/app/src/media
      - ./src/database:/app/src/database
      - ./etetoolkit:/root/.etetoolkit/
    environment:
      - DEBUG=True
      - DJANGO_ENV=development
    command: python src/manage.py runserver 0.0.0.0:8000
