version: '3.8'

services:
  django:
    build:
      context: .
    container_name: speciarium
    ports:
      - "8003:8000"
    volumes:
      - ./src/media:/app/src/media
      - ./src/database:/app/src/database
      - ./etetoolkit:/root/.etetoolkit/
    environment:
      - DEBUG=False
      - DJANGO_ENV=production
    working_dir: /app/src
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    depends_on:
      - postgres
    networks:
      - speciarium_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - speciarium_network

  postgres:
    image: postgres:15
    container_name: postgres_speciarium
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - speciarium_network

volumes:
  postgres_data:

networks:
  speciarium_network: