version: '3.8'

services:
  django:
    build:
      context: .
    container_name: nature
    ports:
      - "8003:8000"
    volumes:
      - ./nature/media:/app/nature/media
      - ./nature/database:/app/nature/database
      - ./etetoolkit:/root/.etetoolkit/
    environment:
      - DEBUG=False
      - DJANGO_ENV=production
    working_dir: /app/nature
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    depends_on:
      - postgres
    networks:
      - nature_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nature_network

  postgres:
    image: postgres:15
    container_name: postgres_species
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .nature/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nature_network

volumes:
  postgres_data:

networks:
  nature_network: